#!/usr/bin/env python

import math
import time
import mysincon 

def plot(mymap, filename):
    fig = plt.figure()
    im = plt.imshow(mymap, cmap=plt.get_cmap('jet'), vmin=0, vmax=255)
    plt.savefig(filename)

def calc(x,y):
    z = 0.0
    for i in range(1,11):
        z += math.sin(math.pow(x,1./i)) * math.cos(math.pow(y,1./i))
    return z

if __name__ == '__main__':
    # --- Pure Python Version ---
    output_pure = []
    start = time.time()
    for x in range(1000):
        line=[]
        for y in range(1000):
            nx = x/100.
            ny = y/100.
            z = calc(nx,ny) * 255
            line.append(z)
        output_pure.append(line)
    end = time.time()
    purepythontime = end - start
    print("Pure Python Time elapsed", purepythontime)

    # Cython Version
    start = time.time()
    output_cython = mysincon.compute_cython()
    end = time.time()
    cythontime = end - start
    
    print("Cythonized Python Time elapsed", cythontime)
    if cythontime > 0:
        print(f"Cython is {purepythontime/cythontime:.2f}x faster")

    # Plotting and Reporting 
    try:
        import matplotlib.pyplot as plt
        # Report the graph generated by pure python
        plot(output_pure, 'sincon_plot_python.pdf')
        # Report the graph generated by the hybrid cython/python
        plot(output_cython, 'sincon_plot_cython.pdf')
        print("Plots saved successfully.")
    except ImportError as err:
        # Bail gracefully if we're using PyPy
        print ("Couldn't import Image or numpy:", str(err))